=== ernsyn/yes-cart/domain-api/src/main/resources/META-INF/schema/export-descriptor-csv.xsd
<!--
  ~ Copyright 2009 Denys Pavlov, Igor Azarnyi
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<!--
    Schema for all import descriptor files.

    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/schema/export-descriptor-csv.xsd"

    This namespace is not actually pointing to the URL for schema, so you need to
    create an alias in your IDE that would point that namespace to this file.

    @author D.Pavlov
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="export-descriptor" type="ExportDescriptorType"/>

    <xs:complexType name="ExportDescriptorType">
        <xs:annotation>
            <xs:documentation>
                Defines the schema for how to represent an export descriptor.
                In general it maps and entity type (by interface) to columns in
                tuples target (e.g. a CSV file).

                File descriptor section specifies file specific configurations and columns
                define the actual mapping for columns to entity type.

                select-sql defines query that is to be used to look up existing object (HSQL)

                Syntax for queries follows HSQL with parameters specified as column names
                in curly brackets.
                e.g.
                    HSQL: select c from CategoryEntity c where c.guid = {guid}
                There are special placeholders in addition to {column} placeholders:
                1. {masterObjectId} PK of the master object
                2. {masterObject} master instance (for use with HSQL)
                3. {GUID} auto generated guid (for use with native SQL inserts)

            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="context" type="ContextType" minOccurs="0"/>
            <xs:element name="entity-type" type="xs:string" minOccurs="1"/>
            <xs:element name="export-file-descriptor" type="ExportFileDescriptorType" minOccurs="1"/>
            <xs:choice>
                <xs:element name="select-sql" type="xs:string" minOccurs="0"/>
                <xs:element name="select-cmd" type="xs:string" minOccurs="0"/>
            </xs:choice>
            <xs:element name="export-columns" type="ExportColumnsType" minOccurs="1"/>
        </xs:sequence>

    </xs:complexType>


    <xs:complexType name="ContextType">
        <xs:annotation>
            <xs:documentation>
                Context defines additional runtime constraints.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="shop-code" type="xs:string" minOccurs="0"/>
                <xs:element name="shop-code-column" type="xs:string" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ExportFileDescriptorType">
        <xs:annotation>
            <xs:documentation>
                File configurations.

                file-name specifies full absolute path to where the export file should be written to.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="file-encoding" type="xs:string"/>
            <xs:element name="file-name" type="xs:string"/>
            <xs:element name="print-header" type="xs:boolean"/>
            <xs:element name="column-delimiter" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="text-qualifier" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="line-end" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ExportColumnsType">
        <xs:sequence>
            <xs:element name="column-descriptor" minOccurs="1" maxOccurs="unbounded" type="ExportColumnType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExportColumnType">
        <xs:annotation>
            <xs:documentation>
                Column header defines the header of a column in a tuple that is represented by
                a property with name (i.e. name element) on the entity type.

                If language defines the values will be attempted to be exported as a i18n.
                The language specified must be exactly the same configuration as Locale used by
                YeS (Yes Shop).

                Field type defines what type of field this is and will define the export strategy
                for that field (e.g. FK_FIELD would fetch a parent entity using lookup-query).
                For FK field entity-type must be specified to auto generate parent dependencies.

                Value regex allows to extract data from the data to allow more control over what
                gets exported from entity. By default group 1 is selected as the value but it is possible
                to define custom group by specifying regex group element.

                Constants just mean that some columns will be prepopulated with values. This is
                useful in some case, as for example setting default online properties for products.

                Lookup query is used to check if the entity exists for normal fields or to retrieve
                parent entities for FK fields. The query syntax follows HSQL (Hibernate) syntax
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="column-header" type="xs:string"/>
            <xs:element name="field-type" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        This field must correspond to org.yes.cart.bulkcommon.csv.ImpExColumn constants.
                        I.e. FIELD, FK_FIELD, SLAVE_INLINE_FIELD, SLAVE_TUPLE_FIELD
                        This field is not restricted to allow more flexibility in custom implementations
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="data-type" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        This field must correspond to org.yes.cart.bulkcommon.model.ImpExValues constants.
                        I.e. STRING, BOOLEAN, LONG, INT, DECIMAL, DATETIME
                        This field is not restricted to allow more flexibility in custom implementations
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="entity-type" type="xs:string" minOccurs="0"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="language" type="xs:string" minOccurs="0"/>
            <xs:element name="context" type="xs:string" minOccurs="0"/>
            <xs:element name="value-regex" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="value-regex-group" type="xs:string" minOccurs="0"/>
                <xs:element name="value-regex-template" type="xs:string" minOccurs="0"/>
            </xs:choice>
            <xs:element name="value-constant" type="xs:string" minOccurs="0"/>
            <xs:element name="lookup-query" type="xs:string" minOccurs="0"/>
            <xs:element name="use-master-object" type="xs:boolean" minOccurs="0"/>
            <xs:element name="export-descriptor" type="ExportDescriptorType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ernsyn/yes-cart/core-modules/core-module-impex/src/test/resources/export/csv/schematest002.xml
<!--
  ~ Copyright 2009 Denys Pavlov, Igor Azarnyi
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<export-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="file:../../../../../../../domain-api/src/main/resources/META-INF/schema/export-descriptor-csv.xsd">

    <context>
        <shop-code>SHOP10</shop-code>
    </context>

    <entity-type>org.yes.cart.domain.entity.Attribute</entity-type>

    <export-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name>attributenames.csv</file-name>
        <print-header>true</print-header>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </export-file-descriptor>

    <select-cmd>select b from AttributeEntity b where b.code = {code}</select-cmd>

    <export-columns>

        <column-descriptor>
            <column-header>Group</column-header>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.AttributeGroup</entity-type>
            <name>attributeGroup</name>
            <context>CTX001</context>
            <lookup-query>select b from AttributeGroupEntity b where b.code = {attributeGroup}</lookup-query>
        </column-descriptor>

        <column-descriptor> <!-- primary key -->
            <column-header>Code</column-header>
            <field-type>FIELD</field-type>
            <name>code</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Name</column-header>
            <field-type>FIELD</field-type>
            <name>name</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Description</column-header>
            <field-type>FIELD</field-type>
            <name>description</name>
            <value-regex>(.{0,4000})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Display Name En</column-header>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>en</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Display Name Ru</column-header>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>ru</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-template>Rus: $1</value-regex-template>
        </column-descriptor>

        <column-descriptor>
            <column-header>Mandatory</column-header>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>mandatory</name>
        </column-descriptor>

        <column-descriptor>
            <column-header>Allow duplicate</column-header>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>allowduplicate</name>
            <value-constant>false</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-header>Allow Failover</column-header>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>allowfailover</name>
            <value-constant>false</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-header>Rank</column-header>
            <field-type>FIELD</field-type>
            <data-type>INT</data-type>
            <name>rank</name>
            <value-constant>500</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-header>Entety Type</column-header>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Etype</entity-type>
            <name>etype</name>
            <lookup-query>select b from EtypeEntity b where b.businesstype = 'String'</lookup-query>
        </column-descriptor>

    </export-columns>
</export-descriptor>

=== ernsyn/yes-cart/core-modules/core-module-impex/src/test/resources/export/csv/productnames.xml
<!--
  ~ Copyright 2009 Denys Pavlov, Igor Azarnyi
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<export-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="file:../../../../../../../domain-api/src/main/resources/META-INF/schema/export-descriptor-csv.xsd">

    <context>
        <shop-code>SHOIP1</shop-code>
    </context>

    <entity-type>org.yes.cart.domain.entity.Product</entity-type>

    <export-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name>target/productnames_export-{timestamp}.csv</file-name>
        <print-header>true</print-header>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </export-file-descriptor>

    <select-sql>select p from ProductEntity p</select-sql>

    <export-columns>

        <!-- Primary key -->
        <column-descriptor>
            <column-header>GUID</column-header>
            <field-type>FIELD</field-type>
            <name>guid</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- SKU code -->
        <column-descriptor>
            <column-header>SKU code</column-header>
            <field-type>FIELD</field-type>
            <name>code</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- Display names -->
        <column-descriptor>
            <column-header>Name En</column-header>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>en</language>
        </column-descriptor>

        <column-descriptor>
            <column-header>Name Ru</column-header>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>ru</language>
        </column-descriptor>

        <!-- brand -->
        <column-descriptor>
            <column-header>Brand</column-header>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Brand</entity-type>
            <name>brand.name</name>
            <value-regex>(.*)</value-regex>
            <value-regex-template>Brand is: $1</value-regex-template>
        </column-descriptor>

        <column-descriptor>
            <column-header>Attribute Slave Inline All</column-header>
            <field-type>SLAVE_INLINE_FIELD</field-type>
            <name>attributes</name>
            <export-descriptor>
                <entity-type>org.yes.cart.domain.entity.AttrValueBrand</entity-type>
                <export-file-descriptor>
                    <file-encoding>UTF-8</file-encoding>
                    <file-name/>
                    <print-header>false</print-header>
                    <column-delimiter>&#09;</column-delimiter>
                    <text-qualifier>#</text-qualifier>
                </export-file-descriptor>
                <select-sql/>
                <export-columns>
                    <column-descriptor>
                        <column-header/>
                        <field-type>FIELD</field-type>
                        <name>attributeCode</name>
                    </column-descriptor>
                    <column-descriptor>
                        <column-header/>
                        <field-type>FIELD</field-type>
                        <name>val</name>
                    </column-descriptor>
                </export-columns>
            </export-descriptor>
        </column-descriptor>

        <column-descriptor>
            <column-header>Attribute Slave Inline Image0</column-header>
            <field-type>SLAVE_INLINE_FIELD</field-type>
            <name>attributes</name>
            <export-descriptor>
                <entity-type>org.yes.cart.domain.entity.AttrValueProduct</entity-type>
                <export-file-descriptor>
                    <file-encoding>UTF-8</file-encoding>
                    <file-name/>
                    <print-header>false</print-header>
                    <column-delimiter>,</column-delimiter>
                    <text-qualifier> </text-qualifier>
                </export-file-descriptor>
                <select-sql>select avp from AttrValueEntityProduct avp where avp.product = {masterObject} and avp.attributeCode = 'IMAGE0'</select-sql>
                <export-columns>
                    <column-descriptor>
                        <column-header/>
                        <field-type>FIELD</field-type>
                        <name>val</name>
                    </column-descriptor>
                </export-columns>
            </export-descriptor>
        </column-descriptor>

        <column-descriptor>
            <column-header>Categories</column-header>
            <field-type>SLAVE_TUPLE_FIELD</field-type>
            <name>productCategory</name>
            <export-descriptor>
                <entity-type>org.yes.cart.domain.entity.AttrValueProduct</entity-type>
                <export-file-descriptor>
                    <file-encoding>UTF-8</file-encoding>
                    <file-name/>
                    <print-header>false</print-header>
                    <column-delimiter>&#09;</column-delimiter>
                    <text-qualifier>#</text-qualifier>
                </export-file-descriptor>
                <select-sql/>
                <export-columns>
                    <column-descriptor>
                        <column-header>Category GUID</column-header>
                        <field-type>FIELD</field-type>
                        <name>category.guid</name>
                    </column-descriptor>
                    <column-descriptor>
                        <column-header>Category Name</column-header>
                        <field-type>FIELD</field-type>
                        <name>category.name</name>
                    </column-descriptor>
                </export-columns>
            </export-descriptor>
        </column-descriptor>

        <column-descriptor>
            <column-header>Attribute by Code</column-header>
            <field-type>FIELD</field-type>
            <data-type>AVC</data-type>
            <name>attributes</name>
            <context>IMAGE0</context>
        </column-descriptor>

        <column-descriptor>
            <column-header>Price by Product ID Currency</column-header>
            <field-type>FIELD</field-type>
            <data-type>PRICE</data-type>
            <name>productId</name>
            <context>USD</context>
        </column-descriptor>

        <column-descriptor>
            <column-header>Price by SKU Currency</column-header>
            <field-type>FIELD</field-type>
            <data-type>PRICE</data-type>
            <name>code</name>
            <context>USD</context>
        </column-descriptor>

    </export-columns>
</export-descriptor>

=== ernsyn/yes-cart/core-modules/core-module-impex/src/test/resources/export/csv/attributenames.xml
<!--
  ~ Copyright 2009 Denys Pavlov, Igor Azarnyi
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<export-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="file:../../../../../../../domain-api/src/main/resources/META-INF/schema/export-descriptor-csv.xsd">

    <entity-type>org.yes.cart.domain.entity.Attribute</entity-type>

    <export-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name>target/attributenames_export-{timestamp}.csv</file-name>
        <print-header>true</print-header>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </export-file-descriptor>

    <select-sql>select b from AttributeEntity b where b.attributeGroup.code = 'PRODUCT'</select-sql>

    <export-columns>

        <column-descriptor>
            <column-header>Group</column-header>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.AttributeGroup</entity-type>
            <name>attributeGroup.code</name>
        </column-descriptor>

        <column-descriptor> <!-- primary key -->
            <column-header>Code</column-header>
            <field-type>FIELD</field-type>
            <name>code</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Name</column-header>
            <field-type>FIELD</field-type>
            <name>name</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Description</column-header>
            <field-type>FIELD</field-type>
            <name>description</name>
            <value-regex>(.{0,4000})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Display Name En</column-header>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>en</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Display Name Ru</column-header>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>ru</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-header>Mandatory</column-header>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>mandatory</name>
        </column-descriptor>

        <column-descriptor>
            <column-header>Allow Dup (Constant)</column-header>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>allowduplicate</name>
            <value-constant>false</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-header>Allow Failver (template)</column-header>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>allowfailover</name>
            <value-regex>(.*)</value-regex>
            <value-regex-template>Failover is: $1</value-regex-template>
        </column-descriptor>

        <column-descriptor>
            <column-header>Rank</column-header>
            <field-type>FIELD</field-type>
            <data-type>INT</data-type>
            <name>rank</name>
            <value-constant>500</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-header>Java Type</column-header>
            <field-type>FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Etype</entity-type>
            <name>etype.javatype</name>
        </column-descriptor>

    </export-columns>
</export-descriptor>
